2022-11-14 18:25:03,121 INFO auth.py login : Login request received
2022-11-14 18:25:03,121 INFO auth.py login : Request contents: ImmutableMultiDict([('username', 'test'), ('password', 'h\x87\x87√ò√ø\x14LP,\x7f\\√ø¬™√æ,√Ö\x88√ò`y√π√û\x880L&¬∞√ã\x99√é\x91√Ü'), ('publicKey', '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxZSZkeqnGfS8ZbFOrmyz\nYxt+aRD/peU5cLLuCNDNCvWZikUWyNaLRSId76lJxMPjFLJq/Vj/NUB7qckoMoPj\n3t7VNjYST7ha2OiR3uBIcKmwDHMnGWKUd4+SYlIZslQRJdxFSq7DA/Gd1Z/nO8tQ\nkJV0d6QHsxYV1l44ROhPSOc+ue79JFLiHocWKbRNforE1P6sbAdWvSu5m75OUTc9\ntnLLY/cQUte1iJJ2hhbq9kCUCpuiIov3TqVGaAfcTpYoedsInJ4C9oFXEDD/cg5M\n8K/lzbPUb+imtP2KUkEq3KH3kOKcmoPtvdZTkk5/rcQQ23nL9FORc554L3aZSOGt\nRwIDAQAB\n-----END PUBLIC KEY-----\n')])
2022-11-14 18:25:03,121 INFO auth.py verifyUser : Looking up in database user: test
2022-11-14 18:25:03,167 ERROR auth.py login : Error: Incorrect username or password.
2022-11-14 18:25:03,168 INFO _internal.py _log : 127.0.0.1 - - [14/Nov/2022 18:25:03] "[31m[1mPOST //auth/login HTTP/1.1[0m" 403 -
2022-11-14 18:25:41,812 INFO auth.py login : Login request received
2022-11-14 18:25:41,813 INFO auth.py login : Request contents: ImmutableMultiDict([('username', 'test'), ('password', '\x8a\x86√Ñ√Æ√è\x12Do√≤s¬Ø√Ä>\x1b:\t¬©\x11√ê¬∑\x98\x1d¬±¬ØX√ãE√Ñ9\x16\x12\x95'), ('publicKey', '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8MyxPCDs2RqR3kSmBZ5C\nOnQClAfSj7UrMgZUjaIw/FZ3jk1vJfXlRBfUVLzPTmmnA9Sd8WmKDYniyMfxOqM/\nT6CLTef3aXwwXI+I0YYBErVEuzlujPJuaq07Vop8jlNowCtvhkr/w731aRKpwjq1\nFCuCyV30luat87UDAANs9RqurSTq/KQmo1qLkRU2vbOHS98S355K2Z/toCHtznyj\nxk0veI81n+endd1Xmw2l4qrPssL2TXITNAsmLaVqkOvhEE8Dhv/jXqXtjXWX9U7i\nWd6tGc6ax7LIyP3W4zwawZeqOMKoyaScHctednyiC8XP6UCkoZjMQBH2pv6NQTBx\nUQIDAQAB\n-----END PUBLIC KEY-----\n')])
2022-11-14 18:25:41,813 INFO auth.py verifyUser : Looking up in database user: test
2022-11-14 18:25:41,885 ERROR auth.py login : Error: Incorrect username or password.
2022-11-14 18:25:41,886 INFO _internal.py _log : 127.0.0.1 - - [14/Nov/2022 18:25:41] "[31m[1mPOST //auth/login HTTP/1.1[0m" 403 -
2022-11-14 18:32:43,153 INFO auth.py login : Login request received
2022-11-14 18:32:43,153 INFO auth.py login : Request contents: ImmutableMultiDict([('username', 'test'), ('password', '\x8a\x86√Ñ√Æ√è\x12Do√≤s¬Ø√Ä>\x1b:\t¬©\x11√ê¬∑\x98\x1d¬±¬ØX√ãE√Ñ9\x16\x12\x95'), ('publicKey', '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmRioJ+z9QEUAESZ+pSLC\n5OIX7zyZauoa60OjPvoHuKZ0TVZFGz7wmST+8iOD4m5jZ7zPH4jzPqRKC734WM5H\nBYzasmwZuQYKDoUUsKowWeE3dsMFMBp+MCEqeVTbs3av3szvXN2eF9yI/9V5Dt0U\nDHvtdS6uEFDR9Hn2SXXZlByIQTbAnsW3702LA/ygFdxInbXY7PJ/x2uZvKcUEUMy\nrxrhT6mAn32FttGEu39P2pqpyjhqR0Yfphe1NU8WUfrnGpNCR319oOQ3SANjX5Ss\nlqICgziwtTjY9gugaKzF/nYMvlP6z1vKsKAmqKA6S8jfE24AevmNtino2nQ7+QG8\n7wIDAQAB\n-----END PUBLIC KEY-----\n')])
2022-11-14 18:32:43,154 INFO auth.py verifyUser : Looking up in database user: test
2022-11-14 18:32:43,211 ERROR auth.py login : Error: Incorrect username or password.
2022-11-14 18:32:43,211 INFO _internal.py _log : 127.0.0.1 - - [14/Nov/2022 18:32:43] "[31m[1mPOST //auth/login HTTP/1.1[0m" 403 -
2022-11-14 18:34:29,540 INFO auth.py login : Login request received
2022-11-14 18:34:29,540 INFO auth.py login : Request contents: ImmutableMultiDict([('username', 'test'), ('password', '\x8a\x86√Ñ√Æ√è\x12Do√≤s¬Ø√Ä>\x1b:\t¬©\x11√ê¬∑\x98\x1d¬±¬ØX√ãE√Ñ9\x16\x12\x95'), ('publicKey', '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz/p4b7Zn0i3Hc6tfE0zN\nx1zr6fAj7NrDiRxS7J8iI46DGAQKp4zGwOfHvmDpE3VtSWz1EOw5dQN4VWcXkLKz\nGU2veT0ZUgNmPQrHCgry17pMrVZqyS/f4CXsse7zqltLWW/8CpuP4Uc501SXFRFg\niTb12kPhvPXsG+hJ1ysWeldqcxhFsjGXdCp04llGs+sQfXGVdaLK5pKbkGU3b7fy\nmxfa8a4KNqEErjpyU+5M0yBycJZICBODNzqsELP5x8HB5RMEp0CSr8FB2e0zSGD3\nhF9BP14KC6aZ2I/A7EooX9mXlWKhIHqD9hpIV1GMef8BBVoBJlgoYQTnfazIYNxS\n+QIDAQAB\n-----END PUBLIC KEY-----\n')])
2022-11-14 18:34:29,541 INFO auth.py verifyUser : Looking up in database user: test
2022-11-14 18:34:29,589 ERROR auth.py login : Error: Incorrect username or password.
2022-11-14 18:34:29,589 INFO _internal.py _log : 127.0.0.1 - - [14/Nov/2022 18:34:29] "[31m[1mPOST //auth/login HTTP/1.1[0m" 403 -
2022-11-14 18:35:11,138 INFO auth.py login : Login request received
2022-11-14 18:35:11,139 INFO auth.py login : Request contents: ImmutableMultiDict([('username', 'test'), ('password', '\x8a\x86√Ñ√Æ√è\x12Do√≤s¬Ø√Ä>\x1b:\t¬©\x11√ê¬∑\x98\x1d¬±¬ØX√ãE√Ñ9\x16\x12\x95'), ('publicKey', '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo+Xofaez8dmDBdec8zNf\nAt7hPye0VGt1fTAJ/vxmFshPzIYe8DLuUJ3FHfWVp3S8Mux37TGfwWPVYmKpcB2b\nJgvh0HpCQ8FP7QetqwHaCRgP1YZBNz/hBU3wt1yuC2hmGDhCP+pXngvovErjRJ3Z\nKL8O4ZrHgQ6QAG9ZAr+HE47WeMPqxOXcP+0w4crrCEQuh2jpJ/j8QFHDiWiniuYP\ngy+8DBqrDuYdepXHYTud4+9XqImeYDphZkVGDGjzqKjRK2jejexNjeAXLFfq4AXt\nFK3RxV5C1YRjIKPxXa/mghXA3vmv9HxpfoAUx3udzGEOIY2f2CJ27puFTh8deE+j\nIQIDAQAB\n-----END PUBLIC KEY-----\n')])
2022-11-14 18:35:11,139 INFO auth.py verifyUser : Looking up in database user: test
2022-11-14 18:35:11,190 ERROR auth.py login : Error: Incorrect username or password.
2022-11-14 18:35:11,191 INFO _internal.py _log : 127.0.0.1 - - [14/Nov/2022 18:35:11] "[31m[1mPOST //auth/login HTTP/1.1[0m" 403 -
2022-11-14 18:35:21,098 INFO auth.py login : Login request received
2022-11-14 18:35:21,098 INFO auth.py login : Request contents: ImmutableMultiDict([('username', 'test'), ('password', '\x9f\x86√ê\x81\x88L}e\x9a/√™\xa0√ÖZ√ê\x15¬£¬øO\x1b+\x0b\x82,√ë]l\x15¬∞√∞\n\x08'), ('publicKey', '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo+Xofaez8dmDBdec8zNf\nAt7hPye0VGt1fTAJ/vxmFshPzIYe8DLuUJ3FHfWVp3S8Mux37TGfwWPVYmKpcB2b\nJgvh0HpCQ8FP7QetqwHaCRgP1YZBNz/hBU3wt1yuC2hmGDhCP+pXngvovErjRJ3Z\nKL8O4ZrHgQ6QAG9ZAr+HE47WeMPqxOXcP+0w4crrCEQuh2jpJ/j8QFHDiWiniuYP\ngy+8DBqrDuYdepXHYTud4+9XqImeYDphZkVGDGjzqKjRK2jejexNjeAXLFfq4AXt\nFK3RxV5C1YRjIKPxXa/mghXA3vmv9HxpfoAUx3udzGEOIY2f2CJ27puFTh8deE+j\nIQIDAQAB\n-----END PUBLIC KEY-----\n')])
2022-11-14 18:35:21,098 INFO auth.py verifyUser : Looking up in database user: test
2022-11-14 18:35:21,142 INFO auth.py login : User test succesfully found
2022-11-14 18:35:21,142 INFO auth.py login : Updating the public key for test
2022-11-14 18:35:21,143 INFO auth.py login : Updated public key of test to:
 -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo+Xofaez8dmDBdec8zNf
At7hPye0VGt1fTAJ/vxmFshPzIYe8DLuUJ3FHfWVp3S8Mux37TGfwWPVYmKpcB2b
Jgvh0HpCQ8FP7QetqwHaCRgP1YZBNz/hBU3wt1yuC2hmGDhCP+pXngvovErjRJ3Z
KL8O4ZrHgQ6QAG9ZAr+HE47WeMPqxOXcP+0w4crrCEQuh2jpJ/j8QFHDiWiniuYP
gy+8DBqrDuYdepXHYTud4+9XqImeYDphZkVGDGjzqKjRK2jejexNjeAXLFfq4AXt
FK3RxV5C1YRjIKPxXa/mghXA3vmv9HxpfoAUx3udzGEOIY2f2CJ27puFTh8deE+j
IQIDAQAB
-----END PUBLIC KEY-----

2022-11-14 18:35:21,145 INFO _internal.py _log : 127.0.0.1 - - [14/Nov/2022 18:35:21] "POST //auth/login HTTP/1.1" 200 -
2022-11-14 18:35:28,490 INFO auth.py login : Login request received
2022-11-14 18:35:28,490 INFO auth.py login : Request contents: ImmutableMultiDict([('username', 'test'), ('password', '\x8a\x86√Ñ√Æ√è\x12Do√≤s¬Ø√Ä>\x1b:\t¬©\x11√ê¬∑\x98\x1d¬±¬ØX√ãE√Ñ9\x16\x12\x95'), ('publicKey', '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0IgUuoKadCgIHFMAQspS\npkmq+nbx5HeFCEL6hgNG8a9GNLD80cOEaLb0jRgz5PW9jZd4vABrbISGLlYEX4sP\nejuthWxTtGZ8QXD456UlFl0SqKuhbHPxdIkE6thd2AsLNQkMUVGpHuZcEpuF/OAK\naSdS+0mTR2FHuU2vWNFlLTbGROzhMohTIel7NStRHlZLWfBYaXygTsE12H++geAK\nZSFS4znZbp8z1DKZ3bHFWtQLOlUyx7c7BRFVR7j9JGbALKfH+kN8mGWyOvb3CHuY\nDPIh6CFAivew1DiQ+wOmewWQ/S+09q84WUDC9dyiWbrD93Xf0MsAzKXQ0tnVX31N\nGQIDAQAB\n-----END PUBLIC KEY-----\n')])
2022-11-14 18:35:28,491 INFO auth.py verifyUser : Looking up in database user: test
2022-11-14 18:35:28,546 ERROR auth.py login : Error: Incorrect username or password.
2022-11-14 18:35:28,546 INFO _internal.py _log : 127.0.0.1 - - [14/Nov/2022 18:35:28] "[31m[1mPOST //auth/login HTTP/1.1[0m" 403 -
2022-11-14 18:35:31,853 INFO auth.py register : Registration request received
2022-11-14 18:35:31,853 INFO auth.py register : Request contents: ImmutableMultiDict([('username', 'test'), ('password', '\x9f\x86√ê\x81\x88L}e\x9a/√™\xa0√ÖZ√ê\x15¬£¬øO\x1b+\x0b\x82,√ë]l\x15¬∞√∞\n\x08'), ('publicKey', '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0IgUuoKadCgIHFMAQspS\npkmq+nbx5HeFCEL6hgNG8a9GNLD80cOEaLb0jRgz5PW9jZd4vABrbISGLlYEX4sP\nejuthWxTtGZ8QXD456UlFl0SqKuhbHPxdIkE6thd2AsLNQkMUVGpHuZcEpuF/OAK\naSdS+0mTR2FHuU2vWNFlLTbGROzhMohTIel7NStRHlZLWfBYaXygTsE12H++geAK\nZSFS4znZbp8z1DKZ3bHFWtQLOlUyx7c7BRFVR7j9JGbALKfH+kN8mGWyOvb3CHuY\nDPIh6CFAivew1DiQ+wOmewWQ/S+09q84WUDC9dyiWbrD93Xf0MsAzKXQ0tnVX31N\nGQIDAQAB\n-----END PUBLIC KEY-----\n')])
2022-11-14 18:35:31,911 INFO auth.py register : Inserting into the database the following user and password
2022-11-14 18:35:31,911 INFO auth.py register : username: test
2022-11-14 18:35:31,911 INFO auth.py register : derived password key: √∫¬∑"=¬≠2:√Ω11¬î¬º$]'f¬•√¨¬π√°nk√¶√ô√Ç√ì√ä ¬ë
2022-11-14 18:35:31,912 ERROR auth.py register : Error: User test is already registered.
2022-11-14 18:35:31,912 INFO _internal.py _log : 127.0.0.1 - - [14/Nov/2022 18:35:31] "[31m[1mPOST //auth/register HTTP/1.1[0m" 403 -
